# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: lishaoh # your blog title name
subtitle:
author: lishaoh # 作者
language: zh-CN
timezone:

# custom Site settings
# more detail check out docs
SEOTitle: lishaoh's blog
header-img: images/home.jpg
email: lsh94753@gmail.com
description: "李少华在 Github 上的个人博客"
keyword: # seo key words

favicon: # your favicon png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: blog.lookpeakfans.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# SNS settings
# RSS:
weibo_username: 5831478442/profile
zhihu_username: lishaoh
github_username: lishaoh
#twitter_username: lishaoh
#facebook_username: lishaoh
#linkedin_username: lishaoh

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username:

# Duoshuo settings
duoshuo_username:  # 你的多说帐号
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Use livere
use_livere:

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar-about-description:  大智若愚 # 个人描述
sidebar-avatar: images/avatar.jpeg    # use absolute URL


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# friends
friends:  # 友链

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/

markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji

## Themes: https://hexo.io/themes/
theme: pure

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Andrew-project/LookPeakBlog.git
  branch: master


# img CDN path
cdn-url:  # 你的CDN地址

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
post-default-img: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1523271490186&di=32a5c4bc5275d71ad5ca11ea4b8899eb&imgtype=0&src=http%3A%2F%2Fwww.jituwang.com%2Fuploads%2Fallimg%2F150830%2F258381-150S011133046.jpg #博文默认的图片
post-default-img-mobile: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1523271603142&di=be4db47c9ddad9cc69dae89ca78f0bec&imgtype=0&src=http%3A%2F%2Fbpic.ooopic.com%2F16%2F67%2F95%2F16679525-a0b2cc218fe33d9819656c5429c3d4c8-3.jpg #移动端显示的图片

# search api , set your custom key
swiftype_key:
nofollow:
  enable: true
  exclude:
    - https://github.com/lishaoh
    - blog.lookpeakfans.xyz
    - http://weibo.com/5831478442/profile

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

jsonContent:
  ignore:
    - path/to/a/page
    - url/to/one/post
    - an-entire-category
    - specific.file
    - .ext # a file extension
neat_enable: true
neat_html:
  enable: ture
  exclude:
neat_css:
  enable: true
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

sitemap:
    path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
# archive page title
archive:
    title: archives
    description: 可以根据归档日期检索所有文件